### ISSUE TITLE
`nim doc module_for_cpp.nim` running `nim js dochack` causes issues with config.nims in parent paths

### ISSUE THREAD

**Issue by timotheecour** [kaushalmodi/std_vector#6] opened 2020-05-30 01:33 UTC
cause of https://github.com/kaushalmodi/std_vector/commit/23ca1ab3602e32c54485baf5e7918382466802dd

when:
* ./config.nims has `switch("backend", "cpp")` eg https://github.com/kaushalmodi/std_vector/blob/23ca1ab3602e32c54485baf5e7918382466802dd/config.nims#L11
* nim is installed under ./
* `nim js tools/dochack/dochack.nim` was not already run
* config.nims will be read by the command that runs nim doc module_for_cpp.nim`
=> causing `Error: This module only works on the JavaScript platform`

## workarounds
* call `nim js tools/dochack/dochack.nim` before the rest
* use a nim that's installed not under ./ so it wont' pickup ./config.nims

## possible longer term solutions
option 1: `nim js tools/dochack/dochack.nim` could be isolated via --skipparentcfg (but might not be a good idea, not sure yet)
option 2:  when nim is built via the `official` way (sh build.sh or sh build_all.sh, TBD; as done in https://github.com/kaushalmodi/std_vector/blob/master/.travis.yml), it should call `nim js tools/dochack/dochack.nim` as part of the build
anything else?

I like option2

## note:
IMO using a nim tha'ts installed under ./ (especially when you have a config.nims that "does things" like changing backend) it seems likely to cause further issues

**Comment by kaushalmodi** [comment] 2020-05-30 04:13
Hello @timotheecour ,

Thank you for that analysis! I can reproduce the issue locally if I put `switch("backend", "cpp")` in a `config.nims` in my nim build directory.

> config.nims will be read by the command that runs nim doc module_for_cpp.nim

I am not sure if the command line `js` should take precedence over the `--backend:cpp` in `config.nims`. But it makes sense that if a user typed `nim js ..`, they literally mean to use that backend and not any other.

> call nim js tools/dochack/dochack.nim before the rest

How can I control that? That `nim js ..` call is happening when I do `nim doc --project ..` [here][1].

> use a nim that's installed not under ./ so it wont' pickup ./config.nims

~I am using choosenim to install nim on Travis.~ Sorry, I got confused by my switch to using choosenim to build on Travis in a different project. But there too, nim will be installed in ~/.choosenim.

---

I am confused .. how do I control when `nim js ..` is run .. it is called internally when running `nim doc --project ..`.

[1]: https://github.com/kaushalmodi/nim_config/blob/84fee8a17f7fca302a4235d8d950ea16e0ee6748/config.nims#L380

**Comment by kaushalmodi** [comment] 2020-05-30 04:16
ok .. this makes sense .. https://github.com/nim-lang/Nim/blob/63d1a0289e872212e836559f92a785df51f4faac/compiler/nimpaths.nim#L42-L45

So may be pre-buiding the dochack.js is a good enough workaround.

**Comment by kaushalmodi** [comment] 2020-05-30 04:22
> when nim is built via the official way (sh build.sh or sh build_all.sh, TBD; as done in https://github.com/kaushalmodi/std_vector/blob/master/.travis.yml), it should call nim js tools/dochack/dochack.nim as part of the build

👍

**Comment by timotheecour** [comment] 2020-05-30 04:58
> But it makes sense that if a user typed nim js .., they literally mean to use that backend and not any other

it's by design, but maybe a bit controversial; eg it allows:
* `nim doc --backend:cpp` (not controversial)
* `nim r --backend:cpp` (not controversial)
* `nim c --backend:cpp` a bit more controversial but useful; it allows overriding commands given as template, eg: `$nim c $options $file % [...] ` where $options can override `c`
* `nim js --backend:cpp` well, i guess that looks a bit more controversial but it's also consistent with the above; and also consistent with fact that `nims` can override command via `setCommand` (a not well known option)

**Comment by kaushalmodi** [comment] 2020-05-30 05:03
When I looked at the .travis.yml of this project again, I remembered that the `-`backend:cpp` caused problems with even building nim .. so it's better off renamed while I finishing building nim and then dochack.js.

Building dochack.js as part of the build.sh definitely makes sense.

That said, the docs of this project are building once again: https://kaushalmodi.github.io/std_vector/.

Thanks!

**Comment by timotheecour** [comment] 2020-05-30 05:03
actually now i forget why you added `switch("backend", "cpp")` in your nims file? I'm not sure that's a good idea... if you're running docs you can do `nim doc --backend:cpp ...`

**Closed as completed by kaushalmodi** 2020-05-30 05:03 UTC

**Comment by kaushalmodi** [comment] 2020-05-30 05:08
I am generating docs using a `docs` task in my global config.nims (which I pull in using the `pullConfig` task in this repo). So adding that switch made sense. That way the same `docs` task can work for all my projects, and I don't need to add if/else conditions in that task to pick the correct backend based on a define, etc.

**Comment by kaushalmodi** [comment] 2020-05-30 05:12
@timotheecour Well, it just occurred to me.. this should fix all the issues: https://github.com/kaushalmodi/std_vector/commit/2acea888cb3892aa8f7ee1e9f81e6bbb3aeb25fd

**Comment by timotheecour** [comment] 2020-05-30 05:13
oh ya that's much cleaner
=> yet another argument in favor of nesting sources under `src` (which some ppl just don't get)

@kaushalmodi 
note that you could've also done this in your master/config.nims:
```nim
selfExec("doc --project --outdir:$1 $2 $3" % [deployDir, docoptions, srcFile])
```

and then for code that uses it:
```
let docoptions = """ -b:cpp --doccmd:"-d:release" """ # for eg
include "nim_config/config.nims"
# => no need for `switch("backend", "cpp")`
```

**Comment by kaushalmodi** [comment] 2020-05-30 05:24
> note that you could've also done this in your master/config.nims:

Then I would either need to define `docoptions` in all the projects using that task or have something like `when not declared(docoptions):` within the `docs` task, right?

**Comment by timotheecour** [comment] 2020-05-30 05:25
`when not declared(docoptions): ` is the way to go -> nothing to change for existing projects

**Comment by kaushalmodi** [comment] 2020-05-30 05:27
As an aside, I wish I didn't need to use `sed` here: https://github.com/kaushalmodi/nim_config/blob/84fee8a17f7fca302a4235d8d950ea16e0ee6748/config.nims#L382-L389

I might need to cook up a `--prettyUrl` switch for `nim doc`.

**Comment by timotheecour** [comment] 2020-05-30 05:40
btw https://kaushalmodi.github.io/std_vector/ docs are starting to look pretty good... if you're interested in improving docs further, there are a number of things we can do, some "fun", other being less "fun" but still needed (... bug fixes)

but all features should be done at the "nim doc" level so that they're enable by default for all projects (including std_vector, and nim's own docs)

 interactive unittests hooking to nim playground
=> see basic description here https://github.com/PMunch/nim-playground-frontend/issues/18 

I think this could actually be a very small PR given what's already available, I can explain more

> As an aside, I wish I didn't need to use sed here:

~~ya you should not, this should be fixed in nim, not user code; how about: `nim doc --project --index:customindex.html`
=> it's just reusing existing `--index` switch instead of adding a new flag (so araq will not complain about "too many switches")~~

* I'm working on a PR to add `git hash`+dirty bit at which nim doc were run

* i noticed your docs don't show "source + edit" links as show in nim's official docs;
=> maybe that PR can automate passing `--git.url:` so user doesnt' have to (which they typically don't do)...

**Comment by kaushalmodi** [comment] 2020-05-30 05:40
I started working on docoptions and then I realized that while that would work on Travis, it won't work in my local env because that nim_config/config.nims is actually my ~/.config/nim/config.nims :)

That config will always get loaded before the project's config.nims.

**Comment by kaushalmodi** [comment] 2020-05-30 05:46
> interactive unittests hooking to nim playground

That's a cool idea. Does it mean that runnableExamples get exported to .json too? So may that happens when user clicks on the Run button?

> ya you should not, this should be fixed in nim, not user code; how about: nim doc --project --index:customindex.html

I don't need to customize the search index or "theindex.html". I'd like to always generate **index.html** as the main or landing page of the project instead of PROJECTNAME.html.

Somewhere you had mentioned that you didn't prefer to have both `--project` and `--out:` switches. Seems like I'd need something like that... `nim doc --project --out:index.html` (the rest of the nested module HTML files will be generated as usual. But the landing page will be `index.html`).

> I'm working on a PR to add git hash+dirty bit at which nim doc were run

👍 

> i noticed your docs don't show "source + edit" links as show in nim's official docs;

Cool, I'll add that.

**Comment by timotheecour** [comment] 2020-05-30 05:48
> I might need to cook up a --prettyUrl switch for nim doc.

(I misunderstod above); shouldn't that be: `nim doc --project -o:htmldocs/mycustomindex.html foo/bar.nim`  ?
although currently IIRC it's buggy as mentioned here https://github.com/nim-lang/Nim/pull/14324

> nim doc --project -o:sub/bar.html main outputs sub/bar.html/main.html ; it's a preexisting odd/buggy behavior from the times outdir didn't exist

**Comment by kaushalmodi** [comment] 2020-05-30 05:49
> nim doc --project -o:htmldocs/mycustomindex.html foo/bar.nim

I had tried that. That creates a directory named `htmldocs/mycustomindex.html/` :/

Essentially, with `--project`, `--out:` behaves the same as `--outdir:`.

**Comment by timotheecour** [comment] 2020-05-30 05:50
right; that's the bug; but if that bug is fixed, then you get what you want right?

**Comment by kaushalmodi** [comment] 2020-05-30 05:50
That's correct.

**Comment by timotheecour** [comment] 2020-05-30 05:53
> That's a cool idea. Does it mean that runnableExamples get exported to .json too? So may that happens when user clicks on the Run button?

for now they may simply get redirected to https://play.nim-lang.org/ but with their runnableExamples pre-populated when they click;

**Comment by kaushalmodi** [comment] 2020-05-30 06:05
argh.. looks like the default branch is "devel": https://github.com/nim-lang/Nim/blob/63d1a0289e872212e836559f92a785df51f4faac/compiler/docgen.nim#L876-L879

We now need a `--git.branch`

**Comment by timotheecour** [comment] 2020-05-30 06:11
i think we can avoid all this and make it automatic so user doesn't even need to provide `--git.branch` etc ; my PR should hopefully handle that.

if you have time to work on a PR for giving proper semantics to `nim doc --project -o:htmldocs/mycustomindex.html foo/bar.nim` that would be great! hopefully it's not controversial, it really is a bug 

EDIT: even if I also specify `--outdir` it's broken:
```
nim doc --project --outdir:htmldocs2 -o:mycustomindex.html -r compiler/nim
Hint: 199189 lines; 4.411s; 439.773MiB peakmem; Debug build; proj: /Users/timothee/git_clone/nim/Nim_devel/compiler/nim; out: /Users/timothee/git_clone/nim/Nim_devel/mycustomindex.html/mycustomindex.html [SuccessX]
The file /Users/timothee/git_clone/nim/Nim_devel/mycustomindex.html/mycustomindex.html does not exist.
```

**Comment by kaushalmodi** [comment] 2020-05-30 06:16
hmm, I just did this locally:

```diff
diff --git a/compiler/docgen.nim b/compiler/docgen.nim
index ffafb1fcb..a37e3ed4f 100644
--- a/compiler/docgen.nim
+++ b/compiler/docgen.nim
@@ -877,7 +877,8 @@ proc genItem(d: PDoc, n, nameNode: PNode, k: TSymKind, docFlags: DocFlags) =
       let defaultBranch =
         if NimPatch mod 2 == 1: "devel"
         else: "version-$1-$2" % [$NimMajor, $NimMinor]
-      let commit = getConfigVar(d.conf, "git.commit", defaultBranch)
+      let gitBranch = getConfigVar(d.conf, "git.branch", defaultBranch)
+      let commit = getConfigVar(d.conf, "git.commit", gitBranch)
       let develBranch = getConfigVar(d.conf, "git.devel", "devel")
       dispA(d.conf, seeSrcRope, "$1", "", [ropeFormatNamedVars(d.conf, docItemSeeSrc,
           ["path", "line", "url", "commit", "devel"], [rope path.string,
```

**Comment by timotheecour** [comment] 2020-05-30 06:17
sure it's easy to do, but IMO this should be done automatically, calling the right git commands, so all projects will automatically benefit from it without having to pass those git branches + hashes manually; that's what my PR shd enable hopefully

**Comment by kaushalmodi** [comment] 2020-05-30 06:20
Cool, my docs task is now evolving as below:

```
  task docs, "Deploy doc html + search index to public/ directory":
    const
      deployDir = root / "public"
    var
      gitUrl = staticExec("cd $1 && git config --get remote.origin.url" % [root])
      gitBranch = staticExec("cd $1 && git symbolic-ref --short HEAD" % [root])
    gitUrl.removeSuffix(".git")
    selfExec("doc --project --outdir:$1 --git.branch:$2 --git.url:$3 $4" % [deployDir, gitBranch, gitUrl, srcFile]) # generates search index and theindex.html too.
```

I believe you'd do something similar in your PR.

**Comment by timotheecour** [comment] 2020-05-30 06:24
precisely :) (but calling from inside `docgen` to avoid `--git.branch` altogether)

**Comment by kaushalmodi** [comment] 2020-05-30 15:50
https://github.com/kaushalmodi/std_vector/issues/6#issuecomment-636281756

> Essentially, with --project, --out: behaves the same as --outdir:.

Opened an issue for this at https://github.com/nim-lang/Nim/issues/14508.
